### ISSUE TITLE
Overlapping actions hide each other

### ISSUE THREAD

**Issue by battlesnake** [andrew-j-armstrong/SCFusion#17]
![image](https://user-images.githubusercontent.com/4949354/110944267-e5b82f00-8344-11eb-87c0-3ad875c57712.png)

There are banshees building during the banshee upgrades, but they aren't shown in the Gantt as the upgrades are drawn on top of the units there.

This Gantt feature is amazing though!  Thanks!  If I could suggest further improvements:

Ability to export it, either as SVG (ideal for me) or PDF or PNG (probably easiest and best for most users).

A way to "play" the Gantt so after choosing a game-speed, a play-head moves across the Gantt. [useful on a second monitor for learning builds]
 - This would likely be a separate program though, rather than part of Super Fusion.
 - It's something that others (e.g. me) could easily probably develop, if the ability to render a Gantt from the exported Fusion XML file was available as a library (or the internal structures + serialisation were available as a library).

I can maybe allocate some time over weekends to contribute - what things would be priority, while taking likely under 3 hours each?

**Comment by xMihai** [comment]
Thanks for the feedback.

I have identified the issue. I'll release a fix in a couple of days.

Exporting to SVG is actually on my "to do" list. It will be included in one of the next releases.

Regarding "playing" the build order, my personal opinion is that the text build order is easier to follow than the Gantt chart when you are executing the build.
I suggest you google "starcraft salt mod". I've never used it myself, but I think it's what you are looking for. I don't know the build order format needed for SALT. If you try it, maybe I can make an output format that can be directly imported in SALT.
